### ISSUE TITLE
Can't render CDK cells

### ISSUE THREAD

**Issue by webbres** [webbres/nodes4knime-cdk2#2]
`Exception in thread "OutPortView-Updater-4" org.knime.core.node.util.InvocationTargetRuntimeException: Exception during execution in Event Dispatch Thread
	at org.knime.core.node.util.ViewUtils.invokeAndWaitInEDT(ViewUtils.java:179)
	at org.knime.core.node.workflow.OutPortView.updateInternal(OutPortView.java:265)
	at org.knime.core.node.workflow.OutPortView$2.run(OutPortView.java:249)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: java.lang.IllegalAccessError: failed to access class org.openscience.cdk.layout.CorrectGeometricConfiguration from class org.openscience.cdk.layout.LayoutHelper (org.openscience.cdk.layout.CorrectGeometricConfiguration is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @bcfbd54; org.openscience.cdk.layout.LayoutHelper is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @73d30c7d)
	at org.openscience.cdk.layout.LayoutHelper.adjustStereo(LayoutHelper.java:27)
	at org.openscience.cdk.knime.type.CDKValueRenderer.setAtomContainer(CDKValueRenderer.java:154)
	at org.openscience.cdk.knime.type.CDKValueRenderer.setValue(CDKValueRenderer.java:200)
	at org.knime.core.data.renderer.AbstractPainterDataValueRenderer.getTableCellRendererComponent(AbstractPainterDataValueRenderer.java:200)
	at org.knime.core.data.renderer.DefaultDataValueRendererFamily.getTableCellRendererComponent(DefaultDataValueRendererFamily.java:217)
	at org.knime.core.data.renderer.SetOfRendererFamilies.getTableCellRendererComponent(SetOfRendererFamilies.java:138)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5738)
	at org.knime.core.node.tableview.TableContentView.prepareRenderer(TableContentView.java:299)
	at org.knime.core.node.tableview.TableContentView.fitCellSizeToRenderer(TableContentView.java:1020)
	at org.knime.core.node.tableview.TableContentView.tableChanged(TableContentView.java:1041)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableStructureChanged(AbstractTableModel.java:217)
	at org.knime.core.node.tableview.TableContentModel.setDataTableIntern(TableContentModel.java:430)
	at org.knime.core.node.tableview.TableContentModel.lambda$0(TableContentModel.java:317)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at org.knime.core.node.util.ViewUtils.invokeAndWaitInEDT(ViewUtils.java:136)
	at org.knime.core.node.tableview.TableContentModel.setDataTable(TableContentModel.java:317)
	at org.knime.core.node.tableview.TableContentView.setDataTable(TableContentView.java:322)
	at org.knime.core.node.tableview.TableView.setDataTable(TableView.java:483)
	at org.knime.core.node.workflow.BufferedDataTableView.updateDataTable(BufferedDataTableView.java:106)
	at org.knime.core.node.workflow.BufferedDataTableView.<init>(BufferedDataTableView.java:92)
	at org.knime.core.node.BufferedDataTable.getViews(BufferedDataTable.java:1138)
	at org.knime.core.node.workflow.OutPortView$3.runWithContext(OutPortView.java:285)
	at org.knime.core.node.workflow.OutPortView$3.run(OutPortView.java:270)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by webbres** [comment]
This appears to only occur when the libs are in a separate plugin.
